version: "2.6"
services:
  db:
    image: postgres:13.8        
    env_file:
        db.env
    # environment:
    #   - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "postgresql_vol01:/var/lib/postgresql/data"
    # ports:
    #  - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2G"
    networks:
      - back_tier

  web:
    build: dbinit-service     
    env_file:
        db.env    
    # ports:
    #  - '8000:8000'
    depends_on:
      - db
    networks:
      - back_tier

  nginx:    
    image: "nginx:latest"
    ports:
      # - "127.0.0.1:9000:9000"
      - "9000:9000"
    volumes:
      - "./nginx_dbinit.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - back_tier
    
volumes:
  postgresql_vol01:
    driver: local

networks:  
  back_tier:
    driver: bridge    